name: Issues print
on:
  issues:
    types: [created]
  push:
    branches:
      - 'main'
jobs:
  handle: 
    runs-on: ubuntu-24.04
    steps: 
      - name: echo_context
        run: echo "${{ toJSON(github.event) }}"
